#!/bin/bash

# Set Python environment (optional)
source ~/miniconda3/etc/profile.d/conda.sh
conda activate RCAEval

SCRIPT="Mitigation/train2.py"

# First, we need to obtain the root causes before training.
# so we run BARO on the original datasets to get the root causes
echo "============================="
echo "Obtain rootcauses before TRAINING using S.O.T.A BARO..."
echo "============================="

datasets=(
    "re2-ob" "re2-ss" "re2-tt"
)
methods=(baro)  
RESULTS_DIR="output/results"
DEST_DIR="output/training_root_cases"

mkdir -p "$DEST_DIR"

for dataset in "${datasets[@]}"; do
    echo "Dataset: $dataset"
    
    cmd="python main.py --dataset $dataset --method ${methods[0]} --research_question RQ_mitigation"

    echo "Running: $cmd"
    eval $cmd


    echo "Selecting 3 containers and 1 file from each..."

    # Get unique container names
    containers=$(ls "$RESULTS_DIR" | cut -d'_' -f1 | sort -u | head -n 3)

    for container in $containers; do
        echo "Processing container: $container"

        # Pick one file from that container
        file=$(ls "$RESULTS_DIR"/${container}_*.json | sort | head -n 1)

        base=$(basename "$file" .json)
        new_name="${base}_${dataset}.json"

        cp "$file" "$DEST_DIR/$new_name"
        echo "Saved: $new_name"
    done

    echo "Finished dataset: $dataset"
done


# Second, we run the training configurations, for all of (Epochs, Temperature, Optimizer).

CRITERIA=(5 10 12)
for crit in "${CRITERIA[@]}"; do
    echo "============================="
    echo "Training Epochs: $crit"
    echo "============================="
    python $SCRIPT --experiment epochs --active_criteria $crit
done
CRITERIA=(0.5 0.7 0.9)
for crit in "${CRITERIA[@]}"; do
    echo "============================="
    echo "Training temperature: $crit"
    echo "============================="
    python $SCRIPT --experiment temperature --active_criteria $crit
done
CRITERIA=("paged_adamw_32bit" "paged_adamw_8bit" "paged_lion_8bit")
for crit in "${CRITERIA[@]}"; do
    echo "============================="
    echo "Training optimizer: $crit"
    echo "============================="
    python $SCRIPT --experiment optimizer --active_criteria $crit
done

echo "All experiments finished."


# Here, we need to obtain the root causes before creating plans (skip if already obtained from RQ1.sh)
echo "============================="
echo "Obtain rootcauses before creating plans using S.O.T.A BARO..."
echo "============================="

datasets=(
    "re1-ob" "re1-ss" "re1-tt"
)
methods=(baro)  
RESULTS_DIR="output/results"
DEST_DIR="output/eval_rootcauses"

mkdir -p "$DEST_DIR"

for dataset in "${datasets[@]}"; do
    echo "Dataset: $dataset"
    
    cmd="python main.py --dataset $dataset --method ${methods[0]} --research_question RQ_mitigation"

    echo "Running: $cmd"
    eval $cmd


    echo "Selecting 3 containers and 1 file from each..."

    # Get unique container names
    containers=$(ls "$RESULTS_DIR" | cut -d'_' -f1 | sort -u | head -n 3)

    for container in $containers; do
        echo "Processing container: $container"

        # Pick one file from that container
        file=$(ls "$RESULTS_DIR"/${container}_*.json | sort | head -n 1)

        base=$(basename "$file" .json)
        new_name="${base}_${dataset}.json"

        cp "$file" "$DEST_DIR/$new_name"
        echo "Saved: $new_name"
    done

    echo "Finished dataset: $dataset"
done

# Finally, we create the plans and evaluate them
# Note: you need to include the generated plans in the evaluation script to evaluate them, and you can also include the generated plans in the evaluation script for RQ1 to compare them with the plans generated by open-source LLMs.
echo "============================="
echo "Creating Plans..."
echo "============================="
python Mitigation/create_plans.py


echo "============================="
echo "Evaluating Plans..."
echo "============================="
python Mitigation/evaluation.py